#!/usr/bin/env node
// Regenerates app.compiled.js from the <script type="text/babel"> block in
// index.html and stamps "<jsx-checksum>+<build-tag>" into
// <html data-compiled-sum="...">.
//
// The inline bootstrap at the end of index.html compares the stamp's part
// before '+' against a checksum of the live JSX at page load: match -> run
// app.compiled.js (no babel-standalone download, no in-browser transpile);
// mismatch or artifact load failure -> fall back to babel-standalone so the
// site still works when someone edits the JSX and forgets to rerun this.
// The full stamp (including the build tag) is the artifact's ?v= cache key,
// so changing the transpile toolchain/options below busts the 1y-immutable
// cache even when the JSX itself is unchanged.
//
// Run after every JSX edit, before committing:  node precompile.js
// (commit app.compiled.js together with index.html — the compiled path has a
// runtime onerror fallback, but shipping a matching stamp without the bundle
// still costs every visitor a failed request + the slow babel path)
'use strict';
const fs = require('fs');
const vm = require('vm');

// must mirror the script tag's data-presets — both paths transpile identically
const PRESETS = ['react'];

const html = fs.readFileSync('index.html', 'utf8');
const m = html.match(/<script type="text\/babel"[^>]*>([\s\S]*?)<\/script>/);
if (!m) { console.error('no text/babel block found'); process.exit(1); }
// the HTML parser normalizes CRLF to LF in script text, so hash what the
// browser will see even if the file ever gets a CRLF checkout
const src = m[1].replace(/\r\n?/g, '\n');

// same checksum the browser bootstrap computes (31-hash + length)
let h = 0;
for (let i = 0; i < src.length; i++) h = (h * 31 + src.charCodeAt(i)) | 0;
const sum = String(h >>> 0) + '-' + src.length;

const sandbox = { window: {}, self: {}, console };
sandbox.window = sandbox;
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync('vendor/babel.min.js', 'utf8'), sandbox);
const out = sandbox.Babel.transform(src, { presets: PRESETS }).code;

// build tag: toolchain fingerprint for the cache key
const toolchain = sandbox.Babel.version + JSON.stringify(PRESETS);
let bh = 0;
for (let i = 0; i < toolchain.length; i++) bh = (bh * 31 + toolchain.charCodeAt(i)) | 0;
const stamp = sum + '+' + String(bh >>> 0).slice(0, 8);

fs.writeFileSync('app.compiled.js',
  '// GENERATED by precompile.js from index.html — do not edit by hand.\n' +
  '// stamp ' + stamp + '\n' + out + '\n');

const stamped = html.replace(
  /(<html[^>]*data-compiled-sum=")[^"]*(")/, '$1' + stamp + '$2');
if (stamped === html && !html.includes('data-compiled-sum="' + stamp + '"')) {
  console.error('data-compiled-sum attribute not found on <html>');
  process.exit(1);
}
fs.writeFileSync('index.html', stamped);
console.log('app.compiled.js written (' + out.length + ' bytes), stamp ' + stamp);
