async page => {
  const origin = new URL(page.url()).origin;
  if (new URL(origin).hostname !== '127.0.0.1') throw new Error('Local client-selection checks only');
  const assert = (value, message) => { if (!value) throw new Error(message); };
  let online = 0;
  const token = 'S'.repeat(43);
  const own = () => ({claimed:true, active:true, synced:true, expires_at:Math.floor(Date.now()/1000)+50*86400,
    subscription_url:'https://www.bnbscheduler.top/campus-connect/subscriptions/'+token+'.txt', online_sessions:online});
  await page.addInitScript(() => Object.defineProperty(navigator, 'clipboard', {value:{writeText:async value => {window.__clientChoiceCopied = value;}}, configurable:true}));
  await page.route('**/api/campus-connect/status', route => route.fulfill({status:200, contentType:'application/json', body:JSON.stringify({available:true, user:{id:81,display_name:'client-choice-fixture'}, csrf_token:'fixture', capacity:10,used:1,remaining:9,subscription:own(),node:{status:'ready'}})}));
  await page.route('**/campus-connect/subscriptions/**', route => route.fulfill({status:200,body:'',headers:{'X-Campus-Node-Name':'MAXCOURSE Campus'}}));
  await page.goto(origin+'/campus-connect/');
  await page.locator('.subscription-card').waitFor();
  assert(await page.locator('.subscription-card #own-client').count()===1, 'Copying a subscription depends on an off-screen client selection');
  await page.locator('#own-client').selectOption('clash');
  assert(await page.locator('.route-source.route-guide').count()===1, 'Routing diagram uses an obsolete standalone configuration action');
  assert((await page.locator('#route-client-logo').getAttribute('src')).endsWith('clash-verge-rev.png'), 'Routing explanation shows the previous client logo');
  assert(await page.locator('#route-client-name').innerText()==='Clash Verge Rev', 'Routing explanation does not follow selected client');
  assert(await page.locator('#routing-mode').inputValue()==='full', 'Clash explanation defaults to a node-only subscription');
  assert((await page.locator('#route-public-policy').innerText()).includes('直接'), 'Full configuration does not explain direct public traffic');
  await page.locator('.route-guide').click();
  await page.locator('#result').waitFor();
  assert(await page.locator('#result').isVisible() && await page.locator('.full-config').evaluate(node=>node.open), 'Full configuration explanation did not lead to usable setup');
  assert(await page.locator('#import-dialog').isHidden(), 'Reading configuration explanation unexpectedly launched import');
  await page.locator('#routing-mode').selectOption('merge');
  await page.locator('.route-guide').click();
  assert(await page.locator('.guide-detail').evaluate(node=>node.open), 'Merged routing explanation did not lead to merge steps');
  assert((await page.locator('#route-public-policy').innerText()).includes('原规则'), 'Merge explanation promises to replace public routing');
  assert(await page.locator('#client-download').getAttribute('href')==='https://github.com/clash-verge-rev/clash-verge-rev/releases', 'Selected client has no matching official download');
  assert((await page.locator('#client-mode').innerText()).includes('规则'), 'Clash setup suggests the wrong routing mode');
  await page.locator('#setup-start').click();
  await page.locator('#import-dialog').waitFor();
  assert((await page.locator('#import-url').inputValue()).endsWith('.yaml'), 'Setup entry imports a different client format');
  assert(await page.locator('[data-import-client=clash]').isVisible(), 'Selected client is absent from import');
  assert(await page.locator('[data-import-client]:visible').count()===1, 'Import does not focus the selected client');
  await page.locator('#import-switch summary').click();
  await page.locator('#import-client').selectOption('stash');
  assert(await page.locator('#own-client').inputValue()==='stash', 'Import client switch does not update the subscription selector');
  assert((await page.locator('[data-import-client=stash]').getAttribute('href')).startsWith('stash://'), 'Import client switch retained the old scheme');
  await page.locator('#import-client').selectOption('clash');
  await page.locator('#import-close').click();
  await page.waitForFunction(()=>document.activeElement?.id==='setup-start');
  await page.getByRole('button',{name:'复制订阅',exact:true}).click();
  assert((await page.evaluate(() => window.__clientChoiceCopied)).endsWith('.yaml'), 'Visible client selection did not determine copied format');
  assert(await page.locator('input[name=client][value=clash]').isChecked(), 'Guide client selection did not synchronize');
  online = 1;
  await page.locator('#own-client').focus();
  await page.evaluate(() => document.dispatchEvent(new Event('visibilitychange')));
  await page.locator('.subscription-metrics').filter({hasText:'1 / 2'}).waitFor();
  assert(await page.locator('#own-client').inputValue()==='clash', 'Status refresh reset selected client');
  assert(await page.locator('#own-client').evaluate(node => node===document.activeElement), 'Automatic status refresh removed keyboard focus');
  await page.locator('input[name=client][value=stash]').check();
  assert(await page.locator('#own-client').inputValue()==='stash', 'Subscription selector did not follow the guide');
  await page.getByRole('button',{name:'二维码',exact:true}).click();
  await page.locator('#subscription-qr svg').waitFor();
  assert(await page.locator('#qr-format').inputValue()==='yaml', 'QR default differs from selected client');
  await page.locator('#import-close').click();
  await page.locator('#own-client').selectOption('shadowrocket');
  assert(await page.locator('#routing-mode').inputValue()==='merge', 'Client switching discarded explicit routing comparison');
  assert((await page.locator('#client-download').getAttribute('href')).includes('id932747118'), 'Shadowrocket download retained the previous client');
  assert((await page.locator('#client-mode').innerText()).includes('配置'), 'Shadowrocket setup lost configuration routing mode');
  await page.getByRole('button',{name:'复制订阅',exact:true}).click();
  assert((await page.evaluate(() => window.__clientChoiceCopied)).endsWith('.txt'), 'Switching back retained YAML format');
  return {selectionBesideActions:true,copyFormat:true,guideSynced:true,refreshPreserved:true,qrFormat:true,officialDownload:true,setupImport:true,setupFocusRestored:true,routingModes:true};
}
