async page => {
  const origin = new URL(page.url()).origin;
  if (new URL(origin).hostname !== '127.0.0.1') throw new Error('Local client-selection checks only');
  const assert = (value, message) => { if (!value) throw new Error(message); };
  let online = 0;
  const token = 'S'.repeat(43);
  const own = () => ({claimed:true, active:true, synced:true, expires_at:Math.floor(Date.now()/1000)+50*86400,
    subscription_url:'https://www.bnbscheduler.top/campus-connect/subscriptions/'+token+'.txt', online_sessions:online});
  await page.addInitScript(() => Object.defineProperty(navigator, 'clipboard', {value:{writeText:async value => {window.__clientChoiceCopied = value;}}, configurable:true}));
  await page.route('**/api/campus-connect/status', route => route.fulfill({status:200, contentType:'application/json', body:JSON.stringify({available:true, user:{id:81,display_name:'client-choice-fixture'}, csrf_token:'fixture', capacity:10,used:1,remaining:9,subscription:own(),node:{status:'ready'}})}));
  await page.route('**/campus-connect/subscriptions/**', route => route.fulfill({status:200,body:'',headers:{'X-Campus-Node-Name':'MAXCOURSE Campus'}}));
  await page.goto(origin+'/campus-connect/');
  await page.locator('.subscription-card').waitFor();
  assert(await page.locator('.subscription-card #own-client').count()===1, 'Copying a subscription depends on an off-screen client selection');
  await page.locator('#own-client').selectOption('clash');
  await page.locator('.sidebar a[href="#setup"]').click();
  assert(await page.locator('#node-panel select').count()===0, 'Status card still asks for configuration choices');
  assert(await page.locator('#node-panel .resource-chips a').count()===2, 'Campus verification entries missing');
  assert(await page.locator('#client-download').getAttribute('href')==='https://github.com/clash-verge-rev/clash-verge-rev/releases', 'Selected client has no matching official download');
  assert((await page.locator('#client-mode').innerText()).includes('规则'), 'Clash setup suggests the wrong routing mode');
  await page.locator('#setup-start').click();
  await page.locator('#import-dialog').waitFor();
  assert((await page.locator('#import-url').inputValue()).endsWith('.yaml'), 'Setup entry imports a different client format');
  assert(await page.locator('[data-import-client=clash]').isVisible(), 'Selected client is absent from import');
  assert(await page.locator('[data-import-client]:visible').count()===1, 'Import does not focus the selected client');
  await page.locator('#import-switch summary').click();
  await page.locator('#import-client').selectOption('stash');
  assert(await page.locator('#own-client').inputValue()==='stash', 'Import client switch does not update the subscription selector');
  assert((await page.locator('[data-import-client=stash]').getAttribute('href')).startsWith('stash://'), 'Import client switch retained the old scheme');
  await page.locator('#import-client').selectOption('clash');
  await page.locator('#import-close').click();
  await page.waitForFunction(()=>document.activeElement?.id==='setup-start');
  await page.getByRole('button',{name:'复制订阅',exact:true}).click();
  assert((await page.evaluate(() => window.__clientChoiceCopied)).endsWith('.yaml'), 'Visible client selection did not determine copied format');
  assert(await page.locator('input[name=client][value=clash]').isChecked(), 'Guide client selection did not synchronize');
  online = 1;
  await page.locator('#own-client').focus();
  await page.evaluate(() => document.dispatchEvent(new Event('visibilitychange')));
  await page.locator('.subscription-metrics').filter({hasText:'1 / 2'}).waitFor();
  assert(await page.locator('#own-client').inputValue()==='clash', 'Status refresh reset selected client');
  assert(await page.locator('#own-client').evaluate(node => node===document.activeElement), 'Automatic status refresh removed keyboard focus');
  await page.locator('input[name=client][value=stash]').check();
  assert(await page.locator('#own-client').inputValue()==='stash', 'Subscription selector did not follow the guide');
  assert(await page.locator('#client-download').getAttribute('href')==='https://stash.ws/zh/download', 'Stash macOS users are sent to the iOS App Store');
  assert(!(await page.locator('#client-store').innerText()).includes('App Store'), 'Stash download guidance excludes the separate Mac distribution');
  await page.getByRole('button',{name:'二维码',exact:true}).click();
  await page.locator('#subscription-qr svg').waitFor();
  assert(await page.locator('#qr-format').inputValue()==='yaml', 'QR default differs from selected client');
  await page.locator('#import-close').click();
  await page.locator('#own-client').selectOption('shadowrocket');
  assert((await page.locator('#client-download').getAttribute('href')).includes('id932747118'), 'Shadowrocket download retained the previous client');
  assert((await page.locator('#client-mode').innerText()).includes('配置'), 'Shadowrocket setup lost configuration routing mode');
  await page.getByRole('button',{name:'复制订阅',exact:true}).click();
  assert((await page.evaluate(() => window.__clientChoiceCopied)).endsWith('.txt'), 'Switching back retained YAML format');
  await page.locator('#own-client').selectOption('flclash');
  await page.reload();await page.locator('.subscription-card').waitFor();
  assert(await page.locator('#own-client').inputValue()==='flclash', 'Returning to the page forgot the user-selected client');
  assert(await page.locator('input[name=client][value=flclash]').isChecked(), 'Restored client did not reach the guide');
  await page.getByRole('button',{name:'复制订阅',exact:true}).click();
  assert((await page.evaluate(()=>window.__clientChoiceCopied)).endsWith('.yaml'), 'Restored client copies an incompatible subscription');
  assert(await page.evaluate(()=>localStorage.getItem('maxcourse-campus-client'))==='flclash', 'Client preference was not saved');
  return {selectionBesideActions:true,copyFormat:true,guideSynced:true,refreshPreserved:true,qrFormat:true,officialDownload:true,setupImport:true,setupFocusRestored:true,compactNode:true,clientRemembered:true};
}
